### PR TITLE
Editorial: Replace backticks with quotes in broken drag-and-drop example

### PR DESCRIPTION
**Pull request by a-sully**
This was accidentally broken in #357

***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/file-system-access/pull/424.html" title="Last updated on Jul 12, 2023, 5:41 PM UTC (8408b9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/file-system-access/424/d8f5556...a-sully:8408b9a.html" title="Last updated on Jul 12, 2023, 5:41 PM UTC (8408b9a)">Diff</a>

### CODE REVIEW

**Comment by mkruisselbrink** [comment]
I'm pretty sure the backticks are intentional? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by inexorabletash** [comment]
Agreed w/ @mkruisselbrink - the backticks seem correct

(I'd just leave an emoji but I was tagged as a reviewer)

**Comment by a-sully** [comment]
https://wicg.github.io/file-system-access/#draganddrop-example is broken as-is (presumably because it's within an <xmp> tag?)

**Comment by inexorabletash** [comment]
Bikeshed was just updated to fix handling of ` in examples. Update and re-run bikeshed locally?

**Comment by a-sully** [comment]
Ah I see. It works locally with backticks. Presumably https://wicg.github.io/file-system-access will update eventually?... Or does it need some trigger (like some PR merging)?

**Comment by inexorabletash** [comment]
I kicked off a re-run of the action. Should be fixed in a few minutes.

**Comment by a-sully** [comment]
Awesome, thanks!

**Comment by inexorabletash** [comment]
Hmmm, didn't seem to do it. I'll keep poking.

**Comment by inexorabletash** [comment]
Okay good now. Needed to rerun the **CI** action, which is a prerequisite and automatically triggers the **pages-build-deployment** action

**Pull request closed without merging**
